//cities
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS"
export const FETCH_CITIES_FAIL = "FETCH_CITIES_FAIL"

//itineraries
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS"
export const FETCH_ITINERARIES_FAIL = "FETCH_ITINERARIES_FAIL"
export const FETCH_ITINERARIES = "FETCH_ITINERARIES"

//users
export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';