//cities
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS"
export const FETCH_CITIES_FAIL = "FETCH_CITIES_FAIL"

//itineraries
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS"
export const FETCH_ITINERARIES_FAIL = "FETCH_ITINERARIES_FAIL"
export const FETCH_ITINERARIES = "FETCH_ITINERARIES"

//users
export const ADD_USER = 'ADD_USER'